apiVersion: training.eduk8s.io/v1alpha1
kind: TrainingPortal
metadata:
  name: tanzu-cloudnative-runtimes
spec:
  portal:
    registration:
      type: anonymous
  workshops:
  - name: lab-markdown-sample
    capacity: 3
    expires: 60m
    orphaned: 5m
