apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: tanzu-cloudnative-runtimes
spec:
  title: Serverless platform usiing Tanzu
  description: A workshop to showcase serverless capabilities in Tanzu
  vendor: eduk8s.io
  difficulty: beginner
  duration: 15m
  url: https://github.com/boskey/educates-learning
  content:
    image: ghcr.io/boskey/educates-terminal
    files: github.com/boskey/educates-learning
  session:
    namespaces:
      budget: small
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
